version: '3.8'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      JASYPT_SECRET_KEY: ${JASYPT_SECRET_KEY}
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '82:82'