version: '3.8'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      JASYPT_SECRET_KEY: ${JASYPT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: dev
      LOG_LEVEL: INFO
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    volumes:
      - /home/tae4an/gcs/gcs-credentials.json:/app/credentials.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  pgdata: