version: '3.8'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      JASYPT_SECRET_KEY: ${JASYPT_SECRET_KEY}
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '80:80'