version: '3.8'
services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - '80:8000'
    environment:
      JASYPT_SECRET_KEY: ${JASYPT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: dev
      LOG_LEVEL: INFO
#    deploy:
#      replicas: 3
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  pgdata: