server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(y4u+tyociJ1VA/RUxxsyEr3tf8ZEKfbUDuPZJnv9RJw3uiWi/YZAuRMl4k0ct+ZmhJmBwCjKXNlpZ9+FjzFlAb5rE1iba73rOo7BPp6PnA2DElgYbFbFBQ==)
    username: ENC(koSJw3jZ7qC1qxXvJpmu4w==)
    password: ENC(Z8QnRjbYd8zc+DI0oKHi9Q==)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        period: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  cloud:
    gcp:
      storage:
        credentials:
          location: ${GOOGLE_APPLICATION_CREDENTIALS}
        project-id: ENC(RGD0LCqXa8dSZzNwqwhc53WR6ITm8YlTFPRzf+StzN8Hh+Ts3ZRXLQ==)
        bucket: smart-office

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    com.google.cloud.storage: DEBUG
    com.google.api.client: DEBUG
    com.office: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.resource: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG

app:
  dir:
    imgdir: file:///C:/SmartOffice/imgs/
    uploadimgdir: C:/SmartOffice/imgs/
    logdir: file:///C:/SmartOffice/logs/
    readLogDir: C:/SmartOffice/logs/