server:
  # SSL 설정 추가
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: ENC(CLTCgFTz0XA+nEThhVb8JfKwC2HECWoGW1fFf9sQsXQ=)
    key-store-type: PKCS12
    key-alias: tomcat
  # 기존 설정 유지
  port: 443  # HTTPS 기본 포트로 변경
  servlet:
    encoding:
      charset: UTF-8
      force: true

# HTTP -> HTTPS 리다이렉션을 위한 추가 포트
http:
  port: 80

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(qFiE9I4v2CXLqZzWNCl7UuJ94DBprPFYECuhR9FpnOn74MinXXgixIHMizfikAUIpC6g9cah12z4z2gjNGtGfLXFwhOc+34dDC681dQfgp4mkHkUfuZRxQ==)
    username: ENC(a0E+w5V96368ZbbGuQA1Kg==)
    password: ENC(pj2nIfjYWFQnQmWpcwEgx3+G834oNjX5bXl3cVDSzCg=)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        period: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false

  cloud:
    gcp:
      storage:
        credentials:
          location: ${GOOGLE_APPLICATION_CREDENTIALS}
        project-id: ENC(RGD0LCqXa8dSZzNwqwhc53WR6ITm8YlTFPRzf+StzN8Hh+Ts3ZRXLQ==)
        bucket: smart-office

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.google.cloud.storage: DEBUG
    com.google.api.client: DEBUG
    com.office: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.resource: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      disable-swagger-default-url: true
      # HTTPS 설정
      url: /v3/api-docs
      config-url: /v3/api-docs/swagger-config
      urls:
        - url: /v3/api-docs
          name: Smart Office API

    api-docs:
      path: /v3/api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
