server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(qFiE9I4v2CXLqZzWNCl7UuJ94DBprPFYECuhR9FpnOn74MinXXgixIHMizfikAUIpC6g9cah12z4z2gjNGtGfLXFwhOc+34dDC681dQfgp4mkHkUfuZRxQ==)
    username: ENC(a0E+w5V96368ZbbGuQA1Kg==)
    password: ENC(pj2nIfjYWFQnQmWpcwEgx3+G834oNjX5bXl3cVDSzCg=)

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      cache:
        period: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false


  cloud:
    gcp:
      storage:
        credentials:
          location: ${GOOGLE_APPLICATION_CREDENTIALS}
        project-id: ENC(RGD0LCqXa8dSZzNwqwhc53WR6ITm8YlTFPRzf+StzN8Hh+Ts3ZRXLQ==)
        bucket: smart-office

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.google.cloud.storage: DEBUG
    com.google.api.client: DEBUG
    com.office: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.resource: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG

app:
  dir:
    imgdir: file:///C:/SmartOffice/imgs/
    uploadimgdir: C:/SmartOffice/imgs/
    logdir: file:///C:/SmartOffice/logs/
    readLogDir: C:/SmartOffice/logs/