server:
  port: 81
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(qFiE9I4v2CXLqZzWNCl7UuJ94DBprPFYECuhR9FpnOn74MinXXgixIHMizfikAUIpC6g9cah12z4z2gjNGtGfLXFwhOc+34dDC681dQfgp4mkHkUfuZRxQ==)
    username: ENC(a0E+w5V96368ZbbGuQA1Kg==)
    password: ENC(pj2nIfjYWFQnQmWpcwEgx3+G834oNjX5bXl3cVDSzCg=)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  security:
#    user:
#      name: admin
#      password: ENC(initialAdminPassword)
#      roles: ADMIN

logging:
  level:
    root: info
    com.office: debug
    jdbc.sqlonly: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off
    org.springframework.web: DEBUG
    org.springframework.web.servlet.view: TRACE
    org.springframework.web.servlet.handler: TRACE
    org.springframework.web.servlet: TRACE

admin:
  url:
    service-url: http://localhost:80    # 서비스 모듈 URL
  security:
    password-policy:
      min-length: 8
      require-special-chars: true
      require-numbers: true
      require-uppercase: true
    login:
      max-attempts: 5
      lock-duration: 30m
  jasypt:
    key:
      algo: PBEWithMD5AndDES