server:
  port: 81
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(qFiE9I4v2CXLqZzWNCl7UuJ94DBprPFYECuhR9FpnOn74MinXXgixIHMizfikAUIpC6g9cah12z4z2gjNGtGfLXFwhOc+34dDC681dQfgp4mkHkUfuZRxQ==)
    username: ENC(a0E+w5V96368ZbbGuQA1Kg==)
    password: ENC(pj2nIfjYWFQnQmWpcwEgx3+G834oNjX5bXl3cVDSzCg=)

mybatis:
  type-aliases-package: com.office.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  level:
    root: info

app:
  url:
    server-url: ${SERVER_URL}

  dir:
    imgdir: file:///C:/SmartOffice/imgs/  # 화면 출력 용
    uploadimgdir: C:/SmartOffice/imgs/    # 파일 Write 용
    logdir: file:///C:/SmartOffice/logs/
    readLogDir: C:/SmartOffice/logs/
  key:
    algo: PBEWithMD5AndDES
